name: barikoi_trace_sdk_flutter_android
description: Android implementation of the barikoi_trace_sdk_flutter plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <4.0.0"

flutter:
  plugin:
    implements: barikoi_trace_sdk_flutter
    platforms:
      android:
        package: com.barikoi.trace_sdk_flutter
        pluginClass: BarikoiTraceSdkFlutterPlugin
        dartPluginClass: BarikoiTraceSdkFlutterAndroid

dependencies:
  flutter:
    sdk: flutter
  barikoi_trace_sdk_flutter_platform_interface:
    path: ../barikoi_trace_sdk_flutter_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^6.0.0
