name: barikoi_trace_sdk_flutter_ios

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/barikoi_trace_sdk_flutter_ios.yaml"
      - "barikoi_trace_sdk_flutter_ios/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/barikoi_trace_sdk_flutter_ios.yaml"
      - "barikoi_trace_sdk_flutter_ios/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.22.0
      working_directory: barikoi_trace_sdk_flutter_ios

