name: barikoi_trace_sdk_flutter
description: Trace users
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

flutter:
  plugin:
    platforms:
      android:
        default_package: barikoi_trace_sdk_flutter_android
      ios:
        default_package: barikoi_trace_sdk_flutter_ios

dependencies:
  flutter:
    sdk: flutter
  barikoi_trace_sdk_flutter_android:
    path: ../barikoi_trace_sdk_flutter_android
  barikoi_trace_sdk_flutter_ios:
    path: ../barikoi_trace_sdk_flutter_ios
  barikoi_trace_sdk_flutter_platform_interface:
    path: ../barikoi_trace_sdk_flutter_platform_interface
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^6.0.0
